sudo: required
services:
  - docker
language: bash
before_install:
  - apt-get update
  - apt-get install -y npm
  - npm install -g @mumbacloud/dmport
script:
  - ./build.sh
branches:
  only:
    - master
