sudo: required
services:
  - docker
language: bash
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y npm
  - ssh -o StrictHostKeyChecking=no git@github.com
  - sudo npm install -g @mumbacloud/dmport
  - docker ps -a
script:
  - ./build.sh
branches:
  only:
    - master
