sudo: required
services:
  - docker
language: bash
before_install:
  - pip install @mumbacloud/dmport
  - export PATH=$PWD/node_modules/.bin:$PATH
script:
  - ./build.sh
branches:
  only:
    - master
