sudo: required
services:
- docker
language: bash
before_install:
- openssl aes-256-cbc -K $encrypted_5e05b97fa0d4_key -iv $encrypted_5e05b97fa0d4_iv
  -in .dm.enc -out .dm -d
- sudo apt-get -qq update
- curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
- sudo apt-get install -y nodejs
- sudo npm install -g @mumbacloud/dmport
script:
- "./build.sh"
branches:
  only:
  - master
notifications:
  slack:
    rooms:
      secure: J1QvvIQLTVg3G6OAfhMumvndus2aUtM3tCXdUxB26/XLZifWSR/haEydyS8+r5oCTA2bxF5wWi8yu5hwLSGrjE/w7ZdJs6mp61Kn9vSSDDSlXYBAHkPPr+D22dWuq9/3Asiir7xoKb/rf8akhxb8cVcT8zoUbNjizxPs4zO+9ufhQdCu8gt8YbksYB7zhmLcIxALCN7FjQ+LiqOOUz07bep1nttSlA6vQoqmtlKiBlpAPhLzI96ZfWFL7SsUCZCOXN9PhaR0g+5uqsyZAuIURAx44Cf6Hn6wD4PJR3IgBAHPK+QienNLJjQVi2pPFN/pgP+IF0qVtlkhvDqLoHSSLbjZqna7L22SbmFNN1XgNDf54NfSNnDSZeR99Ghztr6nuiE9iecE4i4hc9Oa6STrfJPEnuAgdfuYpJ1byrtS/4r6mP4lrIvUvspRcLIo5iT15guIN3Tz7DZ/XvLEuTpL9Mc7lxPVuyZ0bftdgfQakPxN/mNdvnNY2f/q2cmUXcOTbYloN15PnbEiZBtABsMJQKMSnsFoVbw5eCX8PB9TUpN14KxC2eSVlixpmnKqP0ahYAgpEsyQQHgrQJQj/I4cVjcXu6jxKxmppTojlp04chTggmn1czAcH4r0tIKUKbZROWpu+2VE749aWnt6s3jKLanvFVuX9mSd+VusI/Fhwtc=
