sudo: required
services:
- docker
language: bash
before_install:
- openssl aes-256-cbc -K $encrypted_5e05b97fa0d4_key -iv $encrypted_5e05b97fa0d4_iv
  -in .dm.enc -out .dm -d
- sudo apt-get -qq update
- curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
- sudo apt-get install -y nodejs npm
- sudo git clone https://github.com/mumba/dmport /dmport && (cd /dmport && sudo sed
  -e 's%@mumbacloud/dmport%dmport%' -i /dmport/package.json && sudo npm install -g
  )
script:
- "./build.sh"
branches:
  only:
  - master
