sudo: required
services:
  - docker
language: bash
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y -q npm
  - sudo npm install -g https://github.com/mumba/dmport
script:
  - ./build.sh
branches:
  only:
    - master
