sudo: required
services:
  - docker
language: bash
before_install:
  - sudo apt-get update
  - sudo apt-get install -y npm
  - sudo npm install -g @mumbacloud/dmport
script:
  - ./build.sh
branches:
  only:
    - master
