sudo: required
services:
  - docker
language: bash
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y npm
  - mkdir -p ~/.ssh ; echo "StrictHostKeyChecking no" >> ~/.ssh/.config
  - sudo npm install -g @mumbacloud/dmport
  - docker ps -a
script:
  - ./build.sh
branches:
  only:
    - master
