sudo: required
services:
  - docker
language: bash
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -qq -y npm
  - sudo git clone https://github.com/mumba/dmport /dmport && cd /dmport && sudo perl -pie 's%@mumbacloud/dmport%dmport%' /dmport/package.json && sudo npm install -g && sudo ln -s /dmport/index.js /usr/local/bin/dmport
script:
  - ./build.sh
branches:
  only:
    - master
