version: '2'

volumes:
  nvidia_driver:
    external:
      name: "nvidia_driver_384.81"

services:

  staoi:
    container_name: staoi
    hostname: staoi
    build:
      context: .
      dockerfile: Dockerfile.ppc64le
    image: sofwerx/staoi:ppc64le
    volumes:
      - nvidia_driver:/usr/local/nvidia:ro
    devices:
      - /dev/nvidia0
      - /dev/nvidia1
      - /dev/nvidia2
      - /dev/nvidia3
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
    ports:
      - "8000:8000"
    environment:
      CUDA_VISIBLE_DEVICES: "2,3"
      HOST: ${HOST}
    logging:
      driver: json-file
      options:
        max-size: "20k"
    labels:
      - "traefik.backend=staoi"
      - "traefik.port=8000"
      - "traefik.frontend.rule=Host:${STAOI_HOST}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  orient:
    build: orient/
    image: sofwerx/orient
    restart: always
    container_name: orient
    hostname: orient
    environment:
      PEER_CONFIG: "${PEER_CONFIG}"
      NIFI_CONFIG: "{ enabled: false, url: '/nifi' }"
      STAOI_URL: "http://staoi:8000"
      OBJLOB_CONFIG: "{ enabled: true, url: 'http://${STAOI_HOST}:8000/GetObjectLoB' }"
      TRIANGULATE_CONFIG: "{ enabled: true, url: 'http://${STAOI_HOST}:8000/LocateTarget' }"
#      SECURE_PORT: 443
      HTTP_PORT: 9999
    ports:
      - 9999:9999
    labels:
      - "traefik.backend=orient"
      - "traefik.port=9999"
      - "traefik.frontend.rule=Host:${ORIENT_HOST}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"
