version: '2'

volumes:
  traefik-ssl:
    external:
      name: "geo_traefik-ssl"

networks:
  geo_default:
    external:
      name: geo_default

services:

  staoi:
    extends:
      file: docker-compose.yml
      service: staoi
    build:
      context: .
      dockerfile: Dockerfile.x86_64
    image: sofwerx/staoi:x86_64
    networks:
     - geo_default

  orient:
    extends:
      file: docker-compose.yml
      service: orient
    environment:
      REFRESH_CONFIG: '{ triangulate: 2000 }'
    networks:
     - geo_default

  turn:
    extends:
      file: docker-compose.yml
      service: turn
    volumes:
     - traefik-ssl:/ssl
    networks:
     - geo_default

