version: '2'

volumes:
  nvidia_driver:
    external:
      name: "nvidia_driver_384.81"

networks:
  default:
    external:
      name: swxgpu_default

services:

  staoi:
    extends:
      file: docker-compose.yml
      service: staoi
    build:
      context: .
      dockerfile: Dockerfile.ppc64le
    image: sofwerx/staoi:ppc64le
    volumes:
      - nvidia_driver:/usr/local/nvidia:ro
    devices:
      - /dev/nvidia0
      - /dev/nvidia1
      - /dev/nvidia2
      - /dev/nvidia3
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
    environment:
      CUDA_VISIBLE_DEVICES: "0"
#      CUDA_VISIBLE_DEVICES: "2,3"

  orient:
    extends:
      file: docker-compose.yml
      service: orient
    environment:
      REFRESH_CONFIG: '{ triangulate: 500 }'

  turn:
    extends:
      file: docker-compose.yml
      service: turn
    build:
      context: coturn/
      dockerfile: Dockerfile.ppc64le
    image: sofwerx/turn:ppc64le

